# =============================================
# Configuração do banco de dados PostgreSQL
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/pi_car_auto_center
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swing: desabilita modo headless obrigatoriamente
spring.main.banner-mode=off
spring.main.headless=false
