spring.main.web-application-type=none

spring.datasource.url=jdbc:postgresql://localhost:5432/pi_car_auto_center
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl